# Generated by Django 5.2 on 2025-11-30 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('user_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signup Record',
                'verbose_name_plural': 'Signup Records',
                'ordering': ('-created_at',),
            },
        ),
    ]
