# Generated by Django 5.2 on 2025-12-11 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuprecord',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='signuprecord',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='signuprecord',
            index=models.Index(fields=['-created_at'], name='myapp_signu_created_8c5cae_idx'),
        ),
        migrations.AddIndex(
            model_name='signuprecord',
            index=models.Index(fields=['email'], name='myapp_signu_email_9b7873_idx'),
        ),
        migrations.AddIndex(
            model_name='signuprecord',
            index=models.Index(fields=['username'], name='myapp_signu_usernam_037954_idx'),
        ),
    ]
